version: '3'

services:
  activemq:
    image: webcenter/activemq:5.15.2
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - ../_data/activemq/data:/data/activemq
      - ../_data/activemq/log:/var/log/activemq
